Switch to PIMPLE, use COMMA house blockMesh only

diff --git a/roomWindFlow/Allrun b/roomWindFlow/Allrun
--- a/roomWindFlow/Allrun
+++ b/roomWindFlow/Allrun
@@ -6,15 +6,15 @@ cd ${0%/*} || exit 1
 
 ./Allclean
 
-runApplication surfaceFeatures
-if [ $? -ne 0 ]; then
-    echo "ERROR: surfaceFeatures failed"
-    exit 1
-else
-    echo "surfaceFeatures succeeded"
-fi
+#runApplication surfaceFeatures
+#if [ $? -ne 0 ]; then
+    #echo "ERROR: surfaceFeatures failed"
+    #exit 1
+#else
+    #echo "surfaceFeatures succeeded"
+#fi
 
-runApplication blockMesh
+runApplication blockMesh -dict system/blockMeshDictCOMMA
 if [ $? -ne 0 ]; then
     echo "ERROR: blockMesh failed"
     exit 1
@@ -22,13 +22,13 @@ else
     echo "blockMesh succeeded"
 fi
 
-runApplication snappyHexMesh -overwrite
-if [ $? -ne 0 ]; then
-    echo "ERROR: snappyHexMesh failed"
-    exit 1
-else
-    echo "snappyHexMesh succeeded"
-fi
+#runApplication snappyHexMesh -overwrite
+#if [ $? -ne 0 ]; then
+    #echo "ERROR: snappyHexMesh failed"
+    #exit 1
+#else
+    #echo "snappyHexMesh succeeded"
+#fi
 
 runApplication $(getApplication)
 if [ $? -ne 0 ]; then
